-- Inserir o tribunal
INSERT INTO `courts` (`name`, `slug`, `stateUf`, `website`, `createdAt`, `updatedAt`) VALUES
('Tribunal de Justiça de São Paulo', 'tjsp', 'SP', 'https://www.tjsp.jus.br/', NOW(), NOW());

-- Inserir Comarcas
INSERT INTO `judicial_districts` (`name`, `slug`, `courtId`, `stateId`, `zipCode`, `createdAt`, `updatedAt`) VALUES
-- 1ª RAJ - Grande São Paulo
('Arujá', 'aruja', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Barueri', 'barueri', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Carapicuiba', 'carapicuiba', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Cotia', 'cotia', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Diadema', 'diadema', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Embu das Artes', 'embu-das-artes', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Embu-Guaçu', 'embu-guacu', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ferraz de Vasconcelos', 'ferraz-de-vasconcelos', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Guararema', 'guararema', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Guarulhos', 'guarulhos', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Itapecerica da Serra', 'itapecerica-da-serra', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Itapevi', 'itapevi', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Itaquaquecetuba', 'itaquaquecetuba', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Jandira', 'jandira', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Mairiporã', 'mairipora', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Mauá', 'maua', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Mogi das Cruzes', 'mogi-das-cruzes', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Osasco', 'osasco', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Poá', 'poa', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ribeirão Pires', 'ribeirao-pires', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Rio Grande de Serra', 'rio-grande-de-serra', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Santa Isabel', 'santa-isabel', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Santana do Parnaíba', 'santana-do-parnaiba', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Santo André', 'santo-andre', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São Bernardo do Campo', 'sao-bernardo-do-campo', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São Caetano do Sul', 'sao-caetano-do-sul', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São Paulo', 'sao-paulo', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Suzano', 'suzano', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Taboão da Serra', 'taboao-da-serra', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Vargem Grande Paulista', 'vargem-grande-paulista', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
-- 6ª RAJ - Ribeirão Preto
('Altinópolis', 'altinopolis', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Américo Brasiliense', 'americo-brasiliense', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Araraquara', 'araraquara', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Batatais', 'batatais', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Borborema', 'borborema', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Brodowski', 'brodowski', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Caconde', 'caconde', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Cajuru', 'cajuru', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Casa Branca', 'casa-branca', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Cravinhos', 'cravinhos', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Descalvado', 'descalvado', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Franca', 'franca', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Guará', 'guara', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Guariba', 'guariba', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Iacanga', 'iacanga', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ibaté', 'ibate', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ibitinga', 'ibitinga', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Igarapava', 'igarapava', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ipuã', 'ipua', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Itápolis', 'itapolis', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ituverava', 'ituverava', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Jaboticabal', 'jaboticabal', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Jardinópolis', 'jardinopolis', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Matão', 'matao', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Miguelópolis', 'miguelopolis', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Mococa', 'mococa', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Monte Alto', 'monte-alto', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Morro Agudo', 'morro-agudo', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Nuporanga', 'nuporanga', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Orlândia', 'orlandia', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Patrocínio Paulista', 'patrocinio-paulista', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Pedregulho', 'pedregulho', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Pirangi', 'pirangi', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Pitangueiras', 'pitangueiras', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Pontal', 'pontal', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ribeirão Bonito', 'ribeirao-bonito', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Ribeirão Preto', 'ribeirao-preto', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Santa Cruz das Palmeiras', 'santa-cruz-das-palmeiras', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Santa Rosa do Viterbo', 'santa-rosa-do-viterbo', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São Carlos', 'sao-carlos', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São Joaquim da Barra', 'sao-joaquim-da-barra', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São José do Rio Pardo', 'sao-jose-do-rio-pardo', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São Sebastião da Grama', 'sao-sebastiao-da-grama', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('São Simão', 'sao-simao', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Serrana', 'serrana', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Sertãozinho', 'sertaozinho', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Tambaú', 'tambau', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW()),
('Taquaritinga', 'taquaritinga', (SELECT id FROM courts WHERE slug = 'tjsp'), (SELECT id FROM states WHERE uf = 'SP'), NULL, NOW(), NOW())
;
