-- Este script adiciona colunas que podem estar faltando em um schema criado com uma versão anterior dos arquivos.
-- Ele foi projetado para ser executado várias vezes sem causar erros em colunas que já existem.

-- Adicionando colunas à tabela platform_settings
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS site_title VARCHAR(255);
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS site_tagline VARCHAR(255);
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS gallery_image_base_path VARCHAR(255);
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS storage_provider VARCHAR(50);
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS firebase_storage_bucket VARCHAR(255);
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS active_theme_name VARCHAR(100);
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS themes JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS platform_public_id_masks JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS homepage_sections JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS mental_trigger_settings JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS section_badge_visibility JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS map_settings JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS search_pagination_type VARCHAR(50);
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS search_items_per_page INT DEFAULT 12;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS search_load_more_count INT DEFAULT 12;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS show_countdown_on_lot_detail BOOLEAN DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS show_countdown_on_cards BOOLEAN DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS show_related_lots_on_lot_detail BOOLEAN DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS related_lots_count INT DEFAULT 5;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS bidding_settings JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_list_items_per_page INT DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS variable_increment_table JSON;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


-- Adicionando colunas à tabela roles
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS slug VARCHAR(150);

-- Adicionando coluna à tabela lots que pode estar faltando
ALTER TABLE lots ADD COLUMN IF NOT EXISTS `data_ai_hint` VARCHAR(100) NULL;

-- Adicionar colunas faltantes em `bens`
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `data_ai_hint` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `vin` VARCHAR(17) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `renavam` VARCHAR(11) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `engine_power` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `number_of_doors` INT NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `vehicle_options` VARCHAR(500) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `detran_status` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `debts` VARCHAR(500) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `running_condition` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `body_condition` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `tires_condition` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `has_key` BOOLEAN;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `property_type` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `property_registration_number` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `iptu_number` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `is_occupied` BOOLEAN;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `area` DECIMAL(10, 2) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `bedrooms` INT NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `bathrooms` INT NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `parking_spaces` INT NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `amenities` JSON NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `serial_number` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `item_condition` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `specifications` TEXT NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `included_accessories` VARCHAR(500) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `has_invoice` BOOLEAN;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `has_warranty` BOOLEAN;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `repair_history` VARCHAR(500) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `appliance_capacity` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `voltage` VARCHAR(20) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `appliance_type` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `additional_functions` VARCHAR(200) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `hours_used` INT NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `engine_type` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `capacity_or_power` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `maintenance_history` TEXT NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `installation_location` VARCHAR(200) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `complies_with_nr` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `operating_licenses` VARCHAR(200) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `breed` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `age` VARCHAR(30) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `sex` ENUM('Macho', 'Fêmea') NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `weight` VARCHAR(30) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `individual_id` VARCHAR(50) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `purpose` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `sanitary_condition` VARCHAR(200) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `vaccination_status` VARCHAR(200) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `lineage` VARCHAR(200) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `is_pregnant` BOOLEAN;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `special_skills` VARCHAR(200) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `gta_document` VARCHAR(100) NULL;
ALTER TABLE bens ADD COLUMN IF NOT EXISTS `breed_registry_document` VARCHAR(100) NULL;
